
train:
  epoch: 10
  early_stop: 5
  checkpoint: &checkpoint exp/flowse_gldns_libritts_custom
  resume: null
  reload_best_loss: True
  reset_lr: True
  strict: True
  rm_stft: False
  save_period: 1
  seed: 1234


#
model: &model_conf
  tokenizer: pinyin
  tokenizer_path: Emilia_ZH_EN_pinyin/vocab.txt
  audio_drop_prob: 0
  # Empty text is forced into text-drop mode in model/cfm.py. Non-empty text
  # is kept by default; set this > 0 only if additional random text dropping
  # is explicitly desired.
  cond_drop_prob: 0.0

  arch:
    dim: 1024
    depth: 22
    heads: 16
    ff_mult: 2
    text_dim: 512
    conv_layers: 4
    checkpoint_activations: False  # recompute activations and save memory for extra compute
  mel_spec:
    target_sample_rate: 24000
    n_mel_channels: 100
    hop_length: 256
    win_length: 1024
    n_fft: 1024
    mel_spec_type: vocos  # 'vocos' or 'bigvgan'
  vocoder:
    is_local: True  # use local offline ckpt or not
    local_path: /yangliusha02/Model/charactr/vocos-mel-24khz  # local vocoder path

optim:
  lr: 7.5e-6
  warm_up_step: 2500
  max_epoch: 10
  grad_accumulation_steps: 1
  gradient_clip: 5.0



logger:
  path:
  print_freq: 100


datasets:

  train:
    arrow_path: /yangliusha02/F5-TTS/data/GLDNS_LibriTTS_custom/raw.arrow
    split: train
    val_ratio: 0.01
    split_seed: 1234

  val:
    arrow_path: /yangliusha02/F5-TTS/data/GLDNS_LibriTTS_custom/raw.arrow
    split: val
    val_ratio: 0.01
    split_seed: 1234

  dataloader_setting:
    repeat: 1 
    batch_size: 6010
    max_samples: 64
    num_workers: 16
    sample_rate: 16000
    


########################################################
#############       test and eval   ####################
########################################################
infer:

  test:
    checkpoint: /yangliusha02/Model/flowse/wenetspeech4tts_Premium.pt.tar
    cond_type: noisy
    pt_name: wenetspeech4tts_Premium.pt.tar
    use_cuda: True

  save:
    dir: test_out
    fs: 16000

  datareader:
    mix_json: datalist/test/text.json
    mix_dir: datalist/test/noisy
    mix_fs: 16000

  nnet_conf:
    *model_conf
